#!/bin/sh
# 
# sysdriver: launch system driver
#

RETVAL=0

umask 077

case "$1" in
  start)
	echo $"Starting encoder driver module: ---->"
	/sbin/insmod /lib/modules/plmedia.o g_szGBBuffSize=640x480 g_nGBBuffNum=3
	/sbin/insmod /lib/modules/crypt.o
	#echo $"Starting wireless driver module: ---->"
	/sbin/insmod /lib/modules/ic3005_ctrl.o
	cp /etc/RT2870STA.dat /tmp
	/sbin/insmod /lib/modules/rt3070sta.o
	ifconfig ra0 up
	#echo $"Starting ethernet driver module: ---->"
	#/sbin/insmod /lib/modules/mii.o
	/sbin/insmod /lib/modules/sundance.o
    /bin/ping 192.168.1.100 &
    /bin/telnetd -l /bin/login &
	RETVAL=$?
	echo 
	exit $RETVAL
	;;
  stop)
	# donthing
esac
