#!/bin/sh
# tinydb	start tinydb
#

RETVAL=0

umask 077

case "$1" in
  start)
	echo $"Starting TinyDB services: ---->"
	#/usr/sbin/import
	/usr/sbin/import -a /etc/db/actinput.db
	RETVAL=$?
	echo
	exit $RETVAL
	;;
  stop)
	echo $"Shutting down TinyDB services: ---->"
	# donothing 
	echo	
        exit $RETVAL
	;;
esac
