#!/bin/sh
#/bin/write2 0xdb800080 0x51
/bin/mount -t proc proc /proc
/bin/mount -o remount,ro %root% /
/bin/hostname -F /etc/hostname

echo "Disable alignment-fixup function..."
echo "0" > /proc/cpu/alignment

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/rc.d/rcS.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done


/bin/mixer2 -v 80 -0 80
/bin/wavplay /etc/start.wav


echo "Starting webs..."
/bin/sleep 1
/sbin/webs > /dev/console 2>&1
/bin/sleep 3
/bin/runSpook.sh &
