#define UTS_VERSION "#2 Tue Mar 14 12:01:23 CST 2006"
#define LINUX_COMPILE_TIME "12:01:23"
#define LINUX_COMPILE_BY "gary"
#define LINUX_COMPILE_HOST "helix"
#define LINUX_COMPILE_DOMAIN ""
#define LINUX_COMPILER "gcc version 3.3.4"
