#!/bin/sh

RETVAL=0

umask 077

case "$1" in
  start)
        mount -t usbdevfs none /proc/bus/usb
	mkdir /var/etc/ppp
	/sbin/pppoe_monitor &
	RETVAL=$?
	echo
	exit $RETVAL
	;;
  stop)
	# donothing 
esac
